### ISSUE TITLE
TypeError: request.auth.attempt is not a function

### ISSUE THREAD

**Issue by turlup** [adonisjs/adonis-auth#10]
Hi,

When I try :
`yield request.auth.attempt('abc@abc.com', '1234')`
==> Error 500 TypeError: request.auth.attempt is not a function
I have copy past Authentification documentation

Any ideas?

**Comment by thetutlage** [comment]
@turlup Can u tell which authenticator scheme you are using?

**Comment by turlup** [comment]
`authenticator: 'basic',`

**Comment by thetutlage** [comment]
@turlup Each `authenticator` exposes different methods. Check http://adonisjs.com/docs/3.0/authentication#basic-auth

Basic auth is a stateless authentication, which means the end user never logins to a website, instead they send credentials on every request via headers.

So in order to find whether a user is logged in or not, you must use the `check` method, which automatically reads the `request` headers to get user **email** and **password**.

**Comment by turlup** [comment]
OK thanks

**Comment by thetutlage** [comment]
Closing the issue

**Comment by Nigeltiany** [comment]
Its more Intuitive to have a method called check() return a boolean, and attempt() try do something.
Perhaps 

` yield request.auth.attempt() //can take parameters or can work with config/auth.js file settings just like it does now.`
but 
`const basicAuth = request.auth.authenticator('basic'); `
 `yield basicAuth.attempt(); //universal way of attempting to login for state or stateless methods
` 
and 
`request.auth.check() to return a boolean whether the request user is authorized`

**Comment by tomcss** [comment]
I came here because of the same error. The documentation still says to use auth.attempt for basic authentication.

**Comment by RomainLanz** [comment]
Hey @tomcss,

Please, open a new issue with more context.
