### ISSUE TITLE
Adonis Auth facade???

### ISSUE THREAD

**Issue by bot101** [adonisjs/adonis-auth#116]
I don't know if I'm wrong, but Adonisjs doesn't have an Auth facade, and it gets pretty frustrating if the only  way to get access to the auth object is `{request, auth}`. If for instance, I do not want to authenticate a user but retrieve the user's information in a websockets connection (for example) using only a prevoiusly generated auth token, then I'm stuck, because I do not have access to `auth` from socket.io. If there was an auth facade, I'll be able to get the user via `const Auth = use('Auth')`.

**Comment by thetutlage** [comment]
You have got it all wrong.

1. Facade's have nothing to do with what you want.
2. Adonis doesn't use Socket.io
3. Node.js is not a threaded language, so a top-level access to any request information is not possible, since multiple requests are handled concurrently and memory is shared.

If you are new to Node.js, I recommended spending some time of how async programming and Node.js without threads works, before jumping into any framework
