### ISSUE TITLE
 auth.user is set in the method attempt of session schema and is not done in jwt

### ISSUE THREAD

**Issue by urbanogb** [adonisjs/adonis-auth#124]
I have seen another similar question on the same subject, and you answered that when the login is made, the user is not validated since the token was not received.
I do not understand why in the session outline you follow another criterion.
My opinion is that all the schemes should follow the same criteria. And it seems very good to me to update auth.user, simplify my work and understand it very well.

**Comment by thetutlage** [comment]
All schemes follow the same criteria. There is difference between login user and authenticating user session or token.

1. In `login` as an action. You are asking: Validate these credentials and offer a session or a token (in case of JWT) for future. So the user is authenticated but not logged in.

2. In other requests, when the session or JWT is passed to Adonis, this is where `auth.user` will exists, since now the user is authenticated.

**Comment by thetutlage** [comment]
Closing since not actionable
