### ISSUE TITLE
Check for jwt in cookies

### ISSUE THREAD

**Issue by FrancosLab** [adonisjs/adonis-auth#36]
In certain circumstances it's easier to include a jwt as a cookie instead of a header.

What do you think?

**Comment by thetutlage** [comment]
Can u share those circumstances, I believe setting a header will always be more simple. Also since cookies are always sent by browser implicitly, this may open some vulnerabilities.

**Comment by vibe** [comment]
@thetutlage The situation is based when using adonis with something like Next.js, Nuxt.js or Ream. 

Or I assume anything that uses SSR, sometimes we need to SSR an already authenticated page on first load, instead of loading and then checking for auth via XHR,  if we can include the token in the cookie then we can than get that request in the SSR's applications first and then render the authenticated application.

I can provide an example repo with current work around.

Currently, I set a `plainCookie`using adonisJs, and then the ssr application has access to the cookie, I extract the cookie in the SSR application, do an XHR request to AdonisJS to check that the token is valid, and if it is, the SSR application renders the authenticated and prefills a client data store. 

If i do not do this, the client is always initially loaded unauthenticated.

**Comment by koolay** [comment]
I is also a scene that JWT in cookie.

**Comment by vivex** [comment]
is there any custom workaround to support this ?
