### ISSUE TITLE
Get user without request object

### ISSUE THREAD

**Issue by dspangenberg** [adonisjs/adonis-auth#44]
I need the user in multiple models. In Laraval I can do this with

    $user = Auth::user();

Is there something similar in AdonisJS or exists a way to get the authenticated user without access to the request object.

**Comment by thetutlage** [comment]
Short answer - No

Long answer

Node.js handles multiple requests at a time and shares the same memory across. So creating a user global will return wrong information, since the most recent request will reset it.

Also it is nice to have methods with `no side-effects` and pass the user manually from your controller. For example: If you use the same service from command line it will fail, since there is no GLOBAL user.

What I can suggest is create a service class, inject user in the constructor and use it.

**Comment by thetutlage** [comment]
Closing since not actionable
