### ISSUE TITLE
Revoke Token methods are not working like in documentation

### ISSUE THREAD

**Issue by renatomattos2912** [adonisjs/adonis-auth#96]
Hi, i'm trying to revoke the jwt token, but the methods showed in adonis documentation (versions 4.0 and 4.1) is not working (The erro said that the auth.scheme(jwt) is not a function), so i access the tokens database directly using lucid methods and remove all the registries inside token table in database, but for some reason the user continue to login successfully with the deleted token, even with the token database empty, i can not explain why, i don't know what information the auth.check() method is using to validate the token cause there is no token in database to validate. Can you help me to solve this?

**Comment by thetutlage** [comment]
I hope you are using the jwt scheme. Jwt tokens are never saved in the database, since that's how the JWT protocol works, you can read more about it here https://jwt.io/.

In case of `jwt`, you can set a smaller expiry and optionally generate a refresh token, which can be used to re-issue a new JWT token.

The refresh token is saved to the database `tokens` table. So anytime you want to revoke the refresh token, you remove it from the database.

Regarding the code not working, you have to share some code and context for me to help better

**Comment by renatomattos2912** [comment]
Hi @thetutlage, thanks for the answer.

Yes, i'm using the JWT scheme, and i see in the 4.0 and 4.1 documentations that the api schema is no longer accepted, so i do not using api schema, only jwt.

The authentication chapter of the documentation have significant diferentes between 4.0 and 4.1, but any of the versions is working like documentations said, so i think there is a problem with this section.

Bellow is the steps that i'm trying to apply in my code.

1 - Create user:
`async create ({ request }) {
    const { name, email, password } = request.all()

    const user = new User()

    user.name = name
    user.email = email
    user.password = password

    await user.save(user)
  }`

2 - Login user ang get jwt token access and refresh:
`async login ({ request, auth }) {
    const { email, password } = request.all()
    await auth.attempt(email, password)
    return await auth.withRefreshToken().attempt(email, password)
  }`
With this i'm able to call protected endpoints in my api using the jwt token.

3 - Revoke the token (This is where i'm having problems. The code bellow is based on 4.1 doc [4.1 doc](http://adonisjs.com/docs/4.1/authentication):
Ps: the example in 4.1 doc is not working, throw error in the .scheme('jtw') "scheme is not a function", so i changed this to a version where not gives me an error:
`async revokeTokens ({ request, response, auth }) {
    try {
      await auth.check()
      const token = auth.getAuthHeader()
      return await auth.revokeTokens([token])
    } catch (err) {
      response
        .status(404)
        .json({ type: 'error', message: err })
    }
  }`

This code do not give me error, but do not revoke token too, cause even when i'm call this revoke method, i continue to login with the same token that i revoked.

**Comment by renatomattos2912** [comment]
I made some tests, and i understand what you said to me, the jwt token is never revoked, only the refresh token, so ok, i understand this now, but how can i revoke the refresh token? I need to send it in the request? or can i revoke the refresh token using the jwt token (that is what i'm doing)? When i call de revokeTokens method, this method receives the jwt token from header and pass this value to auth.revokeTokens([token]), and the answer is bellow:

```
{
    "n": 0,
    "nModified": 0,
    "ok": 1
}
```

As you can see, nothing was changed in database, not even the 'is_revoked column', so i don't know how to revoke the refresh token.

**Comment by thetutlage** [comment]
So let's understand it from the application flow point of view?

When do you want to revoke the token?

**Comment by renatomattos2912** [comment]
For now i want to be able to create users to have access to my API, and i want to be able to revoke this access any time i want, so the API token that i give to this user needs to be immediately revoked when i put this in blacklist or any other solution that prevents this token to be used again, so the user that have his token revoked will only be able to use my API if i give him another token.

**Comment by glaucomorais** [comment]
I don't know if this issue is up, but we have something somewhat strange between the actual code and what is documented in the website.

I was able to remove the refresh token with this code (the minimum code shown, Adonis 4.1):

```javascript
async logout({ auth, request }) {
    await auth.check();
    await auth.revokeTokens([request.input('refresh_token')], true);
}
```
Like you can see, is different from the documentation that says:

```javascript
const refreshToken = '' // get it from user

await auth
  .scheme('jwt')
  .revokeTokens([refreshToken], true)
```

About the app flows:

In my scenario, when user clicks in the "Logout" link, the Angular app sends the refresh token that is associated with that access to logout endpoint.

I'm working in a way to deny access from a valid JWT token when the user request the access for the device in his/her dashboard (like Facebook or any app you see in the wild) or click in a logout link. To achieve this, I was thinking to use the following aproach:

1. Save anything that identifies the token before to send to user (probably in the `/login` endpoint);
2. The user see a list of those "tokens ids" and select "Remove" or "Revoke" (or simply click in a logout link) and send the token id to a black list ;
3. A middleware check if the request token is blacklisted. If it is, throws a `CE.InvalidJwtToken.invoke()` like exception.

The problem with this approach is _maybe_ the same that @renatomattos2912 is trapped to: identifying the current token.

Any toughts, @thetutlage?

**Comment by RomainLanz** [comment]
Closing since issue hasn't been active for a while.
Feel free to create a new one if needed.

**Comment by vitorcremonez** [comment]
It would be nice if we can revoke JWT on server side based on a hashed tokens.
In auth layer the token passed as parameter can be hashed and make a comparison on database hashed token. If token is not revoked and exists on database so user can act with system. If don't exists or is revoked it auth layer throw an AuthException.

**Comment by RomainLanz** [comment]
JWT aren't stored in the database, therefore you shouldn't and you cannot revoke them. This is how it works and how the spec describe it. If you need to revoke a JWT, maybe you shouldn't use JWT.

**Comment by vitorcremonez** [comment]
What if store a hashed version of token to be able to revoke them and include another infos? Like device info, ip and much more...

**Comment by RomainLanz** [comment]
Doing this remove completely the goal of JWT.
As said before, if you have the need to revoke the token, you shouldn't use a JWT.
